Update pxymon

diff --git a/pxy/pxymon b/pxy/pxymon
--- a/pxy/pxymon
+++ b/pxy/pxymon
@@ -4,13 +4,13 @@
 # ------------------------------
 
 # Go to exe folder
-cd "$HOME/pxy/sys/exe" || { echo "Directory ~/pxy/sys/exe not found"; exit 1; }
+cd "$HOME/pxy/sys" || { echo "Directory ~/pxy/sys/exe not found"; exit 1; }
 
 # Optional: activate virtual environment if needed
 # source ~/pxy/env/bin/activate
 
 # Run the Python script
-python3 exemonpxy.py
+python3 syspxy.py
 
 # Optional: print completion
-echo "exepxy.py execution finished."
+echo "syspxy.py execution finished."
